version: '0.17.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration:
  - Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  # Install scripts. (runs after repo cloning)
environment:
  matrix:
    - nodejs_version: STABLE
      configuration: publish
    - nodejs_version: LTS
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install @types/node --save-dev
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/WebTyped/WebTyped.csproj --verbosity m
  - node --version
  - npm --version
build_script:
  - cmd: dotnet build ./src/WebTyped -c Release -o ./src/WebTyped.Npm/generator/program
  - cmd: node node_modules/typescript/bin/tsc -p ./src/WebTyped.Npm/common/src
  - cmd: node node_modules/typescript/bin/tsc -p ./src/WebTyped.Npm/fetch/src
  - cmd: node node_modules/typescript/bin/tsc -p ./src/WebTyped.Npm/jquery/src
  - cmd: node node_modules/typescript/bin/tsc -p ./src/WebTyped.Npm/angular/src
after_build:
test: off
deploy_script:
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - cd ./src/WebTyped.Npm/common 
  - npm whoami
  - npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
  - npm publish
