version: '0.29.0'
image: Visual Studio 2017
only_commits:
  message: /\[deploy\]/
branches:
  only:
  - master
  - dev
environment:
    matrix:
        - nodejs_version: LTS
configuration:
  - Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
init:
  # - cmd: git config --global core.autocrlf true
  # If not branch master, changes version format
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -ne "master") {Update-AppveyorBuild -Version "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH.$env:APPVEYOR_BUILD_NUMBER"} 
install:
  - ps: |
        $env:DEPLOY_ANNOTATIONS = (
                                    $env:APPVEYOR_REPO_COMMIT_MESSAGE.Contains("[annotations]")-or
                                    $env:APPVEYOR_REPO_COMMIT_MESSAGE.Contains("[all]")
                                  )
        ECHO "Annotations" $env:DEPLOY_ANNOTATIONS
        Install-Product node $env:nodejs_version
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/WebTyped/WebTyped.csproj --verbosity m
build_script:
  ps: |
    if ($env:DEPLOY_ANNOTATIONS -eq $true) {
     dotnet pack ./src/WebTyped.Annotations -c Release
    }
test: off
artifacts:
- path: ./src/WebTyped.Annotations/bin/Release/*.nupkg
  name: nupkgAnnotations
deploy:
  provider: NuGet
  api_key: $(nuget_key)
  skip_symbols: false
  artifact: nupkgAnnotations
  on:
    DEPLOY_ANNOTATIONS: true