version: '0.17.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration:
  - Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  # Install scripts. (runs after repo cloning)
install:
  - npm install
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/WebTyped/WebTyped.csproj --verbosity m
build_script:
  - cmd: dotnet build ./src/WebTyped -c Release -o ./src/WebTyped.Npm/generator/program
  - tsc -p ./src/WebTyped.Npm/common/src
  - tsc -p ./src/WebTyped.Npm/fetch/src
  - tsc -p ./src/WebTyped.Npm/jquery/src
  - tsc -p ./src/WebTyped.Npm/angular/src
after_build:
  - cmd: npm publish ./src/WebTyped.Npm/common/
  - cmd: npm publish ./src/WebTyped.Npm/fetch/
  - cmd: npm publish ./src/WebTyped.Npm/jquery/
  - cmd: npm publish ./src/WebTyped.Npm/angular/
  - cmd: npm publish ./src/WebTyped.Npm/generator/
deploy:
