name: $(Build.SourceBranch)$(rev:.r)
trigger:
  - releases/*

variables:
  rev: $[counter(variables['Build.SourceBranch'], 0)]

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: SetBuildName
      steps:
      - script: echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName).$(Rev)"
        condition: contains(variables['Build.SourceBranch'], '/releases/')
      - script: echo "##vso[build.updatebuildnumber]0.0.0-$(Build.SourceBranchName).$(Rev)"
        condition: not(contains(variables['Build.SourceBranch'], '/releases/'))

    - job: Build
      dependsOn: SetBuildName
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'test/WebTyped.Tests/WebTyped.Tests.csproj'
      - script: dotnet publish ./src/WebTyped.Cli -c Release -o ./src/WebTyped.Npm/cli/program
        displayName: Dotnet - Building and publishing

      - script: npm version $(Build.BuildNumber)
        workingDirectory: src/WebTyped.Npm/cli
        displayName: Setting npm package version

      - powershell: (Get-Content ./README.md) | Set-Content ./src/WebTyped.Npm/cli/README.md
        displayName: npm - updating README

      - script: npm pack
        workingDirectory: src/WebTyped.Npm/cli
        displayName: npm - packing

      - task: PublishPipelineArtifact@1
        inputs:
         artifact: 'tarball'
         targetPath: 'src/WebTyped.Npm/cli/guimabdo-webtyped-$(Build.BuildNumber).tgz'

- stage: Deploy
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'))
  dependsOn: Build
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    environment: npm-guimabdo-webtyped
    displayName: NPM - @guimabdo/webtyped
    strategy:
     runOnce:
       deploy:
         steps:
           - task: DownloadPipelineArtifact@2
             inputs:
              artifactName: 'tarball'
           - task: Npm@1
             inputs:
               command: 'custom'
               workingDir: '$(Pipeline.Workspace)'
               customCommand: 'publish guimabdo-webtyped-$(Build.BuildNumber).tgz --access public'
               customEndpoint: 'npm - guimabdo'
