using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace WebTyped {
	public static class FileHelper {
		public const string Mark = "//*Generated with WebTyped*\r\n";
		public static async Task<string> WriteAsync(string file, string content) {
			//Guarantee directory creation
			var fileInfo = new FileInfo(file);
			fileInfo.Directory.Create();
			
			content = Mark + content;
			string currentContent = null;
			if (File.Exists(file)) {
				currentContent = File.ReadAllText(file);
				if (!currentContent.StartsWith(Mark)) {
					Console.WriteLine($"WebTyped will not change '{file}' because it was possibly generated by someone else. WebTyped will only change files marked with: {Mark}");
					return file;
				}
			}

			if (currentContent != content) {
				Console.WriteLine("changing " + file);
				await File.WriteAllTextAsync(file, content);
			}
			return file;
		}

        public static string PathCombine(params string[] parts)
        {
            return Path.Combine(parts).Replace("\\", "/");
        }
	}
}
